apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orderstep.tasks.chengdai.com
  labels:
    version: "0.1"
spec:
  group: tasks.chengdai.com
  versions:
    - name: v1alpha1
      served: true
      # 其中一个且只有一个版本必需被标记为存储版本
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          # 没有任何内容会被裁剪,哪怕不被识别
          x-kubernetes-preserve-unknown-fields: true
  # 范围是属于namespace的，有 Namespaced 或者 Cluster可以选
  scope: Namespaced
  names:
    plural: ordersteps
    singular: orderstep
    kind:  OrderStep
    listKind: OrderStepList
    shortNames:
      - or
    categories:
      - all